/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaCadastro;

import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelOnda1 = new javax.swing.JLabel();
        jLabelOnda2 = new javax.swing.JLabel();
        jLabelOnda3 = new javax.swing.JLabel();
        jLabellLogologin = new javax.swing.JLabel();
        jLabelLogologin = new javax.swing.JLabel();
        jButtonConcluir1 = new javax.swing.JButton();
        jLabelTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("concluir o procedimento.");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(450, 230, 53, 32);

        jLabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(360, 60, 60, 20);

        jLabelSenha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(360, 100, 60, 20);

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(410, 60, 120, 20);

        jPasswordFieldSenha.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(410, 100, 120, 22);

        jLabelOnda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barrara.png"))); // NOI18N
        getContentPane().add(jLabelOnda1);
        jLabelOnda1.setBounds(0, 160, 300, 140);

        jLabelOnda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barrara.png"))); // NOI18N
        getContentPane().add(jLabelOnda2);
        jLabelOnda2.setBounds(300, 196, 210, 110);

        jLabelOnda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barrara.png"))); // NOI18N
        getContentPane().add(jLabelOnda3);
        jLabelOnda3.setBounds(500, 220, 170, 80);

        jLabellLogologin.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabellLogologin.setText("Login");
        getContentPane().add(jLabellLogologin);
        jLabellLogologin.setBounds(260, -50, 210, 130);

        jLabelLogologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/oie_transparent (4).png"))); // NOI18N
        getContentPane().add(jLabelLogologin);
        jLabelLogologin.setBounds(0, 20, 300, 210);

        jButtonConcluir1.setText("Concluir");
        jButtonConcluir1.setToolTipText("concluir o procedimento.");
        jButtonConcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluir1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConcluir1);
        jButtonConcluir1.setBounds(560, 230, 77, 32);

        jLabelTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Azul.png"))); // NOI18N
        getContentPane().add(jLabelTelaLogin);
        jLabelTelaLogin.setBounds(0, 0, 670, 300);

        setSize(new java.awt.Dimension(688, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonConcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluir1ActionPerformed
        // TODO add your handling code here:
       if(jTextFieldEmail.getText().equals("Sistemajava@gmail.com")&& jPasswordFieldSenha.getText().equals("3211")) {
           System.exit(0);
       }else{
           JOptionPane.showMessageDialog(rootPane, "Erro!.tente novamente");
       }
    }//GEN-LAST:event_jButtonConcluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConcluir1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogologin;
    private javax.swing.JLabel jLabelOnda1;
    private javax.swing.JLabel jLabelOnda2;
    private javax.swing.JLabel jLabelOnda3;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelaLogin;
    private javax.swing.JLabel jLabellLogologin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
