/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

import Connection.ConnectionFactory;
import javax.persistence.EntityManager;

/**
 *
 * @author Erick
 */
public class concessionaria extends javax.swing.JFrame {

    /**
     * Creates new form concessionaria
     */
    public concessionaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelFundo2 = new javax.swing.JLabel();
        jLabelConcessionaria = new javax.swing.JLabel();
        jLabelFundo1 = new javax.swing.JLabel();
        jButtonLojaMoto = new javax.swing.JButton();
        jButtonLojaCarro1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 240, 90, 60);

        jLabelFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundo2.setText("Saur");
        getContentPane().add(jLabelFundo2);
        jLabelFundo2.setBounds(0, 242, 543, 53);

        jLabelConcessionaria.setBackground(new java.awt.Color(255, 255, 255));
        jLabelConcessionaria.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelConcessionaria.setForeground(new java.awt.Color(0, 0, 0));
        jLabelConcessionaria.setText("concessionaria");
        getContentPane().add(jLabelConcessionaria);
        jLabelConcessionaria.setBounds(200, 0, 170, 40);

        jLabelFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundo1.setText("concessionária");
        getContentPane().add(jLabelFundo1);
        jLabelFundo1.setBounds(0, 0, 543, 53);

        jButtonLojaMoto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLojaMoto.setForeground(new java.awt.Color(102, 255, 255));
        jButtonLojaMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/motoo.png"))); // NOI18N
        jButtonLojaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLojaMotoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLojaMoto);
        jButtonLojaMoto.setBounds(210, 170, 130, 40);

        jButtonLojaCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/carro.png"))); // NOI18N
        jButtonLojaCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLojaCarro1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLojaCarro1);
        jButtonLojaCarro1.setBounds(210, 100, 130, 40);

        setSize(new java.awt.Dimension(559, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLojaCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLojaCarro1ActionPerformed
        // TODO add your handling code here:
        //Formas de acessar a tabela carros.
        TelaCarro tela = new TelaCarro();
        tela.setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButtonLojaCarro1ActionPerformed

    private void jButtonLojaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLojaMotoActionPerformed
        // TODO add your handling code here:
        TelaMoto telaMoto = new TelaMoto();
        telaMoto.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonLojaMotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(concessionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(concessionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(concessionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(concessionaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new concessionaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLojaCarro1;
    private javax.swing.JButton jButtonLojaMoto;
    private javax.swing.JLabel jLabelConcessionaria;
    private javax.swing.JLabel jLabelFundo1;
    private javax.swing.JLabel jLabelFundo2;
    // End of variables declaration//GEN-END:variables
}
