/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

/**
 *
 * @author Erick
 */
public class TelaMoto extends javax.swing.JFrame {

    /**
     * Creates new form TelaMoto
     */
    public TelaMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoMoto = new javax.swing.JLabel();
        jMenuBarraMoto = new javax.swing.JMenuBar();
        jMenuVoltaMoto = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelFundoMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoMoto.setText("concessionária");
        getContentPane().add(jLabelFundoMoto);
        jLabelFundoMoto.setBounds(0, -30, 650, 430);

        jMenuBarraMoto.setBackground(new java.awt.Color(204, 204, 204));

        jMenuVoltaMoto.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVoltaMoto.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVoltaMoto.setText("Volta");
        jMenuBarraMoto.add(jMenuVoltaMoto);

        jMenu2.setBackground(new java.awt.Color(204, 204, 204));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Edit");
        jMenuBarraMoto.add(jMenu2);

        setJMenuBar(jMenuBarraMoto);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoMoto;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarraMoto;
    private javax.swing.JMenu jMenuVoltaMoto;
    // End of variables declaration//GEN-END:variables
}
