/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

import Connection.ConnectionFactory;
import ModelDAO.volkswagenDAO;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import model.Volkswagen;

/**
 *
 * @author Erick
 */
public class TelaCarroVolkswagen extends javax.swing.JFrame {

    /**
     * Creates new form TelaCarroVolkswagen
     */
    public TelaCarroVolkswagen() {
        initComponents();
        this.mostraTabela();
    }
    //Mostrando a tabela do Banco De Dados
    public void mostraTabela() {
        EntityManager em = new ConnectionFactory().getConnection();
        volkswagenDAO volkswagen = new volkswagenDAO();
        List<Volkswagen> tabelaVolkswagen = new ArrayList();
        DefaultTableModel tabela = new DefaultTableModel();
        this.jTableCarrosChevrolet.setModel(tabela);
        
            tabela.addColumn("Id Placa Final");
            tabela.addColumn("Nome do Carro");
            tabela.addColumn("Ano");
            tabela.addColumn("Qtd Veiculos");
            tabela.addColumn("Cor do carro");
            tabela.addColumn("Portas");
            tabela.addColumn("Cambio");
            tabela.addColumn("Valor");
            
            for(Volkswagen c: volkswagen.getBuscarCarros()) {
                tabela.addRow(
                new Object[] {
                c.getIdfinalplaca(),
                c.getNomecarro(),
                c.getAno(),
                c.getQuantidadecarros(),
                c.getCor(),
                c.getPortas(),
                c.getCambio(),
                c.getValor()   
                 }
                
                );
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameTabela = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrosChevrolet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonFechaTabelaDecarros = new javax.swing.JButton();
        jLabelFundoCarro1 = new javax.swing.JLabel();
        jMenuBarraTarefa = new javax.swing.JMenuBar();
        jMenuVoltar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuTabelaCarro = new javax.swing.JMenu();
        jMenuItemAbrirTabelaVolkswaen = new javax.swing.JMenuItem();
        jMenuVendeCarro = new javax.swing.JMenu();
        jMenuItemVenderCarro = new javax.swing.JMenuItem();
        jMenusSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameTabela.setTitle("Bem-Vindo-Tabela Volkswagen");
        jInternalFrameTabela.setVisible(true);
        jInternalFrameTabela.getContentPane().setLayout(null);

        jTableCarrosChevrolet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableCarrosChevrolet);

        jInternalFrameTabela.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 610, 360);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tabela Volkswagen");
        jInternalFrameTabela.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 30);

        jButtonFechaTabelaDecarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fecha2.png"))); // NOI18N
        jButtonFechaTabelaDecarros.setToolTipText("Fecha tela bem-vindo Na loja de carro");
        jButtonFechaTabelaDecarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTabelaDecarrosActionPerformed(evt);
            }
        });
        jInternalFrameTabela.getContentPane().add(jButtonFechaTabelaDecarros);
        jButtonFechaTabelaDecarros.setBounds(550, 0, 50, 40);

        getContentPane().add(jInternalFrameTabela);
        jInternalFrameTabela.setBounds(0, 30, 610, 330);

        jLabelFundoCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoCarro1.setText("concessionária");
        getContentPane().add(jLabelFundoCarro1);
        jLabelFundoCarro1.setBounds(-10, -40, 750, 510);

        jMenuBarraTarefa.setBackground(new java.awt.Color(204, 204, 204));

        jMenuVoltar.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVoltar.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVoltar.setText("Voltar");

        jMenuItem1.setText("Volta Para Tabela Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVoltar.add(jMenuItem1);

        jMenuBarraTarefa.add(jMenuVoltar);

        jMenuTabelaCarro.setBackground(new java.awt.Color(204, 204, 204));
        jMenuTabelaCarro.setForeground(new java.awt.Color(0, 0, 0));
        jMenuTabelaCarro.setText("Abrir Tabela Carro");

        jMenuItemAbrirTabelaVolkswaen.setText("Abrir Tabela Volkswagen");
        jMenuItemAbrirTabelaVolkswaen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirTabelaVolkswaenActionPerformed(evt);
            }
        });
        jMenuTabelaCarro.add(jMenuItemAbrirTabelaVolkswaen);

        jMenuBarraTarefa.add(jMenuTabelaCarro);

        jMenuVendeCarro.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVendeCarro.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVendeCarro.setText("Vender Carro");

        jMenuItemVenderCarro.setText("Vende Carro");
        jMenuVendeCarro.add(jMenuItemVenderCarro);

        jMenuBarraTarefa.add(jMenuVendeCarro);

        jMenusSair.setBackground(new java.awt.Color(204, 204, 204));
        jMenusSair.setForeground(new java.awt.Color(0, 0, 0));
        jMenusSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenusSair.add(jMenuItemSair);

        jMenuBarraTarefa.add(jMenusSair);

        setJMenuBar(jMenuBarraTarefa);

        setSize(new java.awt.Dimension(622, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFechaTabelaDecarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTabelaDecarrosActionPerformed
        // TODO add your handling code here:
        jInternalFrameTabela.dispose();
        
    }//GEN-LAST:event_jButtonFechaTabelaDecarrosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAbrirTabelaVolkswaenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirTabelaVolkswaenActionPerformed
        // TODO add your handling code here:
        TelaCarroVolkswagen telacarro = new TelaCarroVolkswagen();
        telacarro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAbrirTabelaVolkswaenActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaCarro telaCarro = new TelaCarro();
        telaCarro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarroVolkswagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarroVolkswagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarroVolkswagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarroVolkswagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarroVolkswagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaTabelaDecarros;
    private javax.swing.JInternalFrame jInternalFrameTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoCarro1;
    private javax.swing.JMenuBar jMenuBarraTarefa;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAbrirTabelaVolkswaen;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVenderCarro;
    private javax.swing.JMenu jMenuTabelaCarro;
    private javax.swing.JMenu jMenuVendeCarro;
    private javax.swing.JMenu jMenuVoltar;
    private javax.swing.JMenu jMenusSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarrosChevrolet;
    // End of variables declaration//GEN-END:variables
}
