/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

import Connection.ConnectionFactory;
import ModelDAO.ClienteDAO;
import javax.persistence.EntityManager;
import model.Cliente;

/**
 *
 * @author Erick
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        EntityManager em = new ConnectionFactory().getConnection();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabelLogoCliente = new javax.swing.JLabel();
        jPanelAleatorio = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonSalvaCliente = new javax.swing.JButton();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jTextFieldNomeCompleto1 = new javax.swing.JTextField();
        jButtonFechaTabelaDeMotos = new javax.swing.JButton();
        jLabelFundoCarro1 = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelLogoCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLogoCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogoCliente.setText("Cadastro Cliente");
        getContentPane().add(jLabelLogoCliente);
        jLabelLogoCliente.setBounds(160, 0, 220, 40);

        jPanelAleatorio.setBackground(new java.awt.Color(102, 102, 102));
        jPanelAleatorio.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelAleatorio.add(jButton1);
        jButton1.setBounds(20, 240, 64, 32);

        jButtonSalvaCliente.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSalvaCliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvaCliente.setText("Cria Conta");
        jButtonSalvaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaClienteActionPerformed(evt);
            }
        });
        jPanelAleatorio.add(jButtonSalvaCliente);
        jButtonSalvaCliente.setBounds(410, 240, 100, 32);

        jLabelCpf.setBackground(new java.awt.Color(153, 51, 255));
        jLabelCpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCpf.setText("Cpf:");
        jPanelAleatorio.add(jLabelCpf);
        jLabelCpf.setBounds(110, 110, 100, 40);

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });
        jPanelAleatorio.add(jTextFieldCpf);
        jTextFieldCpf.setBounds(230, 80, 150, 20);

        jLabelNomeCompleto.setBackground(new java.awt.Color(153, 51, 255));
        jLabelNomeCompleto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNomeCompleto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeCompleto.setText("Nome Completo:");
        jPanelAleatorio.add(jLabelNomeCompleto);
        jLabelNomeCompleto.setBounds(110, 70, 120, 40);

        jTextFieldNomeCompleto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCompleto1ActionPerformed(evt);
            }
        });
        jPanelAleatorio.add(jTextFieldNomeCompleto1);
        jTextFieldNomeCompleto1.setBounds(150, 120, 150, 20);

        jButtonFechaTabelaDeMotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fecha2.png"))); // NOI18N
        jButtonFechaTabelaDeMotos.setToolTipText("Fecha tela bem-vindo Na loja de carro");
        jButtonFechaTabelaDeMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTabelaDeMotosActionPerformed(evt);
            }
        });
        jPanelAleatorio.add(jButtonFechaTabelaDeMotos);
        jButtonFechaTabelaDeMotos.setBounds(480, 0, 50, 40);

        getContentPane().add(jPanelAleatorio);
        jPanelAleatorio.setBounds(0, 0, 540, 330);

        jLabelFundoCarro1.setBackground(new java.awt.Color(102, 102, 102));
        jLabelFundoCarro1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelFundoCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoCarro1.setText("concessionária");
        getContentPane().add(jLabelFundoCarro1);
        jLabelFundoCarro1.setBounds(-10, -40, 750, 510);

        setSize(new java.awt.Dimension(549, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jButtonSalvaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaClienteActionPerformed
        // TODO add your handling code here:
        //Salvando os Dados no botão para salva no Banco de dados
        EntityManager em = new ConnectionFactory().getConnection();  
        ClienteDAO clientedao = new ClienteDAO();
        Cliente ClienteControll = new Cliente();
        
        ClienteControll.setNome(this.jTextFieldNomeCompleto1.getText());
        ClienteControll.setCpf(this.jTextFieldCpf.getText());

        clientedao.getSalva(ClienteControll);
         this.jTextFieldNomeCompleto1.setText("");
         this.jTextFieldCpf.setText("");
        
        
    }//GEN-LAST:event_jButtonSalvaClienteActionPerformed
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaCarro Carro = new TelaCarro();
        Carro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeCompleto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCompleto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCompleto1ActionPerformed

    private void jButtonFechaTabelaDeMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTabelaDeMotosActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonFechaTabelaDeMotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFechaTabelaDeMotos;
    private javax.swing.JButton jButtonSalvaCliente;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelFundoCarro1;
    private javax.swing.JLabel jLabelLogoCliente;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JPanel jPanelAleatorio;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldNomeCompleto1;
    // End of variables declaration//GEN-END:variables
}
