/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

import Connection.ConnectionFactory;
import ModelDAO.ChevroletDAO;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import model.Chevrolet;

/**
 *
 * @author Erick
 */
public class TelaCarroChevrolete extends javax.swing.JFrame {

    /**
     * Creates new form TelaCarroChevrolete
     */
    public TelaCarroChevrolete() {
        initComponents();
        this.mostraTabela();
    }
    public void mostraTabela() {
        //Mostrando a tabela do Banco De Dados
        EntityManager em = new ConnectionFactory().getConnection();
        ChevroletDAO chevrolete = new ChevroletDAO();
        List<Chevrolet> tabelaChevrolete = new ArrayList();
        DefaultTableModel tabela = new DefaultTableModel();
        this.jTableCarrosChevrolet.setModel(tabela);
            
            tabela.addColumn("Id Placa Final");
            tabela.addColumn("Nome do Carro");
            tabela.addColumn("Ano");
            tabela.addColumn("Qtd Veiculos");
            tabela.addColumn("Cor do carro");
            tabela.addColumn("Portas");
            tabela.addColumn("Cambio");
            tabela.addColumn("Valor");
            
            for(Chevrolet c :chevrolete.getBuscarCarros() ) {
                tabela.addRow(
                new Object[] {
              c.getIdfinalplaca(),
              c.getNomecarro(),
              c.getAno(),
              c.getQuantidadecarros(),
              c.getCor(),
              c.getPortas(),
              c.getCambio(),
              c.getValor()
                }
                
                
                );
            }
                    
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoCarro = new javax.swing.JLabel();
        jInternalFrameTabela = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrosChevrolet = new javax.swing.JTable();
        jButtonFechaTabelaDecarros = new javax.swing.JButton();
        jLabelTabelaCarro = new javax.swing.JLabel();
        jLabelFundoCarro1 = new javax.swing.JLabel();
        jMenuBarMenuCarro = new javax.swing.JMenuBar();
        jMenuVoltar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuAbrirTabelaCarro = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuVendeCarro = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabelFundoCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoCarro.setText("concessionária");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameTabela.setTitle("Bem-Vindo Na Loja De Carro");
        jInternalFrameTabela.setVisible(true);
        jInternalFrameTabela.getContentPane().setLayout(null);

        jTableCarrosChevrolet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableCarrosChevrolet);

        jInternalFrameTabela.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 660, 360);

        jButtonFechaTabelaDecarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fecha2.png"))); // NOI18N
        jButtonFechaTabelaDecarros.setToolTipText("Fecha tela bem-vindo Na loja de carro");
        jButtonFechaTabelaDecarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTabelaDecarrosActionPerformed(evt);
            }
        });
        jInternalFrameTabela.getContentPane().add(jButtonFechaTabelaDecarros);
        jButtonFechaTabelaDecarros.setBounds(610, 0, 50, 40);

        jLabelTabelaCarro.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTabelaCarro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTabelaCarro.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTabelaCarro.setText("Tabela Chevrolet");
        jInternalFrameTabela.getContentPane().add(jLabelTabelaCarro);
        jLabelTabelaCarro.setBounds(0, 10, 170, 20);

        getContentPane().add(jInternalFrameTabela);
        jInternalFrameTabela.setBounds(0, 30, 720, 370);

        jLabelFundoCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoCarro1.setText("concessionária");
        getContentPane().add(jLabelFundoCarro1);
        jLabelFundoCarro1.setBounds(-10, -40, 750, 510);

        jMenuBarMenuCarro.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBarMenuCarro.setForeground(new java.awt.Color(51, 51, 51));

        jMenuVoltar.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVoltar.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVoltar.setText("Voltar");

        jMenuItem1.setText("Volta Para Tela De Tabela Carros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVoltar.add(jMenuItem1);

        jMenuBarMenuCarro.add(jMenuVoltar);

        jMenuAbrirTabelaCarro.setBackground(new java.awt.Color(204, 204, 204));
        jMenuAbrirTabelaCarro.setForeground(new java.awt.Color(0, 0, 0));
        jMenuAbrirTabelaCarro.setText("Abrir Tabela Carro");

        jMenuItem2.setText("Abrir Tabela Chevrolet");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAbrirTabelaCarro.add(jMenuItem2);

        jMenuBarMenuCarro.add(jMenuAbrirTabelaCarro);

        jMenuVendeCarro.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVendeCarro.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVendeCarro.setText("Vender Carro");
        jMenuBarMenuCarro.add(jMenuVendeCarro);

        jMenuSair.setBackground(new java.awt.Color(204, 204, 204));
        jMenuSair.setForeground(new java.awt.Color(0, 0, 0));
        jMenuSair.setText("Sair");

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem3);

        jMenuBarMenuCarro.add(jMenuSair);

        setJMenuBar(jMenuBarMenuCarro);

        setSize(new java.awt.Dimension(675, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFechaTabelaDecarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTabelaDecarrosActionPerformed
        // TODO add your handling code here:
        jInternalFrameTabela.dispose();

    }//GEN-LAST:event_jButtonFechaTabelaDecarrosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaCarroChevrolete telaChevrolete = new TelaCarroChevrolete();
        telaChevrolete.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaCarro telaCarro = new TelaCarro();
        telaCarro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarroChevrolete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarroChevrolete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarroChevrolete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarroChevrolete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarroChevrolete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaTabelaDecarros;
    private javax.swing.JInternalFrame jInternalFrameTabela;
    private javax.swing.JLabel jLabelFundoCarro;
    private javax.swing.JLabel jLabelFundoCarro1;
    private javax.swing.JLabel jLabelTabelaCarro;
    private javax.swing.JMenu jMenuAbrirTabelaCarro;
    private javax.swing.JMenuBar jMenuBarMenuCarro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVendeCarro;
    private javax.swing.JMenu jMenuVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarrosChevrolet;
    // End of variables declaration//GEN-END:variables
}
