/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoProjeto;

import Connection.ConnectionFactory;
import ModelDAO.bmwDAO;
import ModelDAO.motoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import model.Bmw;
import model.Motos;

/**
 *
 * @author Erick
 */
public class TelaMoto extends javax.swing.JFrame {

    /**
     * Creates new form TelaMoto
     */
    public TelaMoto() {
        initComponents();
        this.initComplementosMostraTabela();
    }
    
    //Mostra Tabela Completa;
    public void initComplementosMostraTabela() {
        this.setLocationRelativeTo(null);
        EntityManager em = new ConnectionFactory().getConnection();  
     motoDAO motos = new motoDAO();
     List<Motos> TabelaMotos = new ArrayList();
     DefaultTableModel tabela = new DefaultTableModel();
     this.jTableMotos.setModel(tabela);
      
        tabela.addColumn("Id Placa Final");
        tabela.addColumn("Nome do Motos");
        tabela.addColumn("Ano");
        tabela.addColumn("Qtd De Motos");
        tabela.addColumn("Cor da Motos");
        tabela.addColumn("Cambio");
        tabela.addColumn("Valor");
        
      for(Motos c: motos.getBuscarTodos()) {
          tabela.addRow(
          new Object[] {
              c.getIdfinalplaca(),
              c.getNomemotos(),
              c.getAno(),
              c.getQuantidademoto(),
              c.getCor(),
              c.getCambio(),
              c.getValor()
          }
          );
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameTabelaMotos = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotos = new javax.swing.JTable();
        jButtonFechaTabelaDeMotos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoMoto = new javax.swing.JLabel();
        jMenuBarraMoto = new javax.swing.JMenuBar();
        jMenuVoltaMoto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuAbrirTabela = new javax.swing.JMenu();
        jMenuItemTabelaMotos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameTabelaMotos.setTitle("Bem-Vindo Na Loja De Motos");
        jInternalFrameTabelaMotos.setVisible(true);
        jInternalFrameTabelaMotos.getContentPane().setLayout(null);

        jTableMotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTableMotos);

        jInternalFrameTabelaMotos.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 630, 360);

        jButtonFechaTabelaDeMotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fecha2.png"))); // NOI18N
        jButtonFechaTabelaDeMotos.setToolTipText("Fecha tela bem-vindo Na loja de carro");
        jButtonFechaTabelaDeMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTabelaDeMotosActionPerformed(evt);
            }
        });
        jInternalFrameTabelaMotos.getContentPane().add(jButtonFechaTabelaDeMotos);
        jButtonFechaTabelaDeMotos.setBounds(580, 0, 50, 40);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tabela Motos:");
        jInternalFrameTabelaMotos.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 130, 30);

        getContentPane().add(jInternalFrameTabelaMotos);
        jInternalFrameTabelaMotos.setBounds(0, 30, 640, 330);

        jLabelFundoMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Barra.png"))); // NOI18N
        jLabelFundoMoto.setText("concessionária");
        getContentPane().add(jLabelFundoMoto);
        jLabelFundoMoto.setBounds(0, -20, 650, 430);

        jMenuBarraMoto.setBackground(new java.awt.Color(204, 204, 204));

        jMenuVoltaMoto.setBackground(new java.awt.Color(204, 204, 204));
        jMenuVoltaMoto.setForeground(new java.awt.Color(0, 0, 0));
        jMenuVoltaMoto.setText("Volta");

        jMenuItem1.setText("Volta Para Tabelas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVoltaMoto.add(jMenuItem1);

        jMenuBarraMoto.add(jMenuVoltaMoto);

        jMenuAbrirTabela.setBackground(new java.awt.Color(204, 204, 204));
        jMenuAbrirTabela.setForeground(new java.awt.Color(0, 0, 0));
        jMenuAbrirTabela.setText("Abrir Tabela Motos");

        jMenuItemTabelaMotos.setText("Abrir Tabela Motos");
        jMenuItemTabelaMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTabelaMotosActionPerformed(evt);
            }
        });
        jMenuAbrirTabela.add(jMenuItemTabelaMotos);

        jMenuBarraMoto.add(jMenuAbrirTabela);

        jMenuSair.setBackground(new java.awt.Color(204, 204, 204));
        jMenuSair.setForeground(new java.awt.Color(0, 0, 0));
        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBarraMoto.add(jMenuSair);

        jMenu1.setText("Vende Moto");

        jMenuItem2.setText("Vende Motos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBarraMoto.add(jMenu1);

        setJMenuBar(jMenuBarraMoto);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFechaTabelaDeMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTabelaDeMotosActionPerformed
        // TODO add your handling code here:
       jInternalFrameTabelaMotos.dispose();

    }//GEN-LAST:event_jButtonFechaTabelaDeMotosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaCarro carro = new TelaCarro();
        carro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemTabelaMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTabelaMotosActionPerformed
        // TODO add your handling code here:
        TelaMoto moto = new TelaMoto();
        moto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTabelaMotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaTabelaDeMotos;
    private javax.swing.JInternalFrame jInternalFrameTabelaMotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoMoto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAbrirTabela;
    private javax.swing.JMenuBar jMenuBarraMoto;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTabelaMotos;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVoltaMoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMotos;
    // End of variables declaration//GEN-END:variables
}
